sudo: required

dist: focal

language: node_js

node_js:
 - "20"
services:
  - docker

before_install:
 - docker build -t piyush/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true piyush/react-test npm test -- --coverage


after_success:
 - docker build -t abpj150/multi-client:latest ./client
 - docker build -t abpj150/multi-nginx:latest ./nginx
 - docker build -t abpj150/multi-server:latest ./server
 - docker build -t abpj150/multi-worker:latest ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push abpj150/multi-nginx:latest
 - docker push abpj150/multi-client:latest
 - docker push abpj150/multi-server:latest
 - docker push abpj150/multi-worker:latest





